version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_es
    environment:
      POSTGRES_USER: es
      POSTGRES_PASSWORD: es
      POSTGRES_DB: es
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
